home:
      pattern: /
      parameters:
        _controller: Front@Home::index
        methods:  [GET]
        routeName: home
Foo:
      pattern: /foo
      parameters:
        _controller: Front@Foo::index
        methods:  [GET]
        routeName: Foo